/**
 * This file was auto-generated by pocketbase-zod-schema.
 * Do not modify it manually.
 */

export interface ContainerImagesRecord {
  id: string;
  created: string;
  updated: string;
  collectionId: string;
  collectionName: 'ContainerImages';
  ContainerRef: string;
  ImageRef: string;
  boundingBox?: any;
}

export interface ContainerImagesResponse extends ContainerImagesRecord {
  expand?: {
    ContainerRef?: ContainersResponse;
    ImageRef?: ImagesResponse;
  };
}

export interface ContainerRecordsRecord {
  id: string;
  created: string;
  updated: string;
  collectionId: string;
  collectionName: 'ContainerRecords';
  ContainerRef: string;
  UserRef: string;
  transactionType: 'create' | 'update' | 'delete';
  fieldName?: string;
  newValue: string;
}

export interface ContainerRecordsResponse extends ContainerRecordsRecord {
  expand?: {
    ContainerRef?: ContainersResponse;
    UserRef?: UsersResponse;
  };
}

export interface ContainersRecord {
  id: string;
  created: string;
  updated: string;
  collectionId: string;
  collectionName: 'Containers';
  containerLabel: string;
  containerNotes?: string;
  ImageRef?: string;
  boundingBox?: any;
  UserRef: string;
}

export interface ContainersResponse extends ContainersRecord {
  expand?: {
    ImageRef?: ImagesResponse;
    UserRef?: UsersResponse;
  };
}

export interface ImageMetadataRecord {
  id: string;
  created: string;
  updated: string;
  collectionId: string;
  collectionName: 'ImageMetadata';
  fileHash: string;
  metadata: any;
  version?: number;
  imageType?: 'item' | 'container' | 'unprocessed';
}

export interface ImageMetadataResponse extends ImageMetadataRecord {}

export interface ImagesRecord {
  id: string;
  created: string;
  updated: string;
  collectionId: string;
  collectionName: 'Images';
  file: string;
  fileHash?: string;
  imageType?: 'item' | 'container' | 'unprocessed';
  analysisStatus?: 'pending' | 'processing' | 'completed' | 'failed';
  UserRef: string;
}

export interface ImagesResponse extends ImagesRecord {
  expand?: {
    UserRef?: UsersResponse;
  };
}

export interface ItemImagesRecord {
  id: string;
  created: string;
  updated: string;
  collectionId: string;
  collectionName: 'ItemImages';
  ItemRef: string;
  ImageRef: string;
  boundingBox?: any;
}

export interface ItemImagesResponse extends ItemImagesRecord {
  expand?: {
    ItemRef?: ItemsResponse;
    ImageRef?: ImagesResponse;
  };
}

export interface ItemRecordsRecord {
  id: string;
  created: string;
  updated: string;
  collectionId: string;
  collectionName: 'ItemRecords';
  ItemRef: string;
  UserRef: string;
  transactionType: 'create' | 'update' | 'delete';
  fieldName?: string;
  newValue: string;
}

export interface ItemRecordsResponse extends ItemRecordsRecord {
  expand?: {
    ItemRef?: ItemsResponse;
    UserRef?: UsersResponse;
  };
}

export interface ItemsRecord {
  id: string;
  created: string;
  updated: string;
  collectionId: string;
  collectionName: 'Items';
  itemLabel: string;
  itemName?: string;
  itemNotes?: string;
  categoryFunctional: string;
  categorySpecific: string;
  itemType: string;
  itemManufacturer?: string;
  itemAttributes?: any;
  ContainerRef?: string;
  ImageRef?: string;
  boundingBox?: any;
  UserRef: string;
}

export interface ItemsResponse extends ItemsRecord {
  expand?: {
    ContainerRef?: ContainersResponse;
    ImageRef?: ImagesResponse;
    UserRef?: UsersResponse;
  };
}

export interface UsersRecord {
  id: string;
  created: string;
  updated: string;
  collectionId: string;
  collectionName: 'Users';
  name?: string;
  avatar?: string;
}

export interface UsersResponse extends UsersRecord {}

export type CollectionResponses = {
  ContainerImages: ContainerImagesResponse;
  ContainerRecords: ContainerRecordsResponse;
  Containers: ContainersResponse;
  ImageMetadata: ImageMetadataResponse;
  Images: ImagesResponse;
  ItemImages: ItemImagesResponse;
  ItemRecords: ItemRecordsResponse;
  Items: ItemsResponse;
  Users: UsersResponse;
};

import PocketBase from 'pocketbase';
import { RecordService } from 'pocketbase';

export interface TypedPocketBase extends PocketBase {
  collection(idOrName: string): RecordService;
  collection(
    idOrName: 'ContainerImages'
  ): RecordService<ContainerImagesResponse>;
  collection(
    idOrName: 'ContainerRecords'
  ): RecordService<ContainerRecordsResponse>;
  collection(idOrName: 'Containers'): RecordService<ContainersResponse>;
  collection(idOrName: 'ImageMetadata'): RecordService<ImageMetadataResponse>;
  collection(idOrName: 'Images'): RecordService<ImagesResponse>;
  collection(idOrName: 'ItemImages'): RecordService<ItemImagesResponse>;
  collection(idOrName: 'ItemRecords'): RecordService<ItemRecordsResponse>;
  collection(idOrName: 'Items'): RecordService<ItemsResponse>;
  collection(idOrName: 'Users'): RecordService<UsersResponse>;
}
